"use client";

import { useEffect, useState } from "react";

type Event = { event_id: string; source_timestamp: string; content: string; tickers: string[]; classification: { severity?: string; direction?: string; ignored: boolean } };
const tabs = ["Overview", "Alerts", "Market", "Sources", "Settings"];
const tabInfo: Record<string, string> = {
  Overview: "P0 pipeline status: ingestion, normalization, classification, routing and dashboard visibility.",
  Alerts: "Every alert shows the event, assets, expected direction, severity and confidence when available.",
  Market: "Market verification compares price, volume, bid depth, open interest and funding around an event.",
  Sources: "Shows each source adapter, its documented API status and whether it is live, fixture-only or blocked.",
  Settings: "Shows safe notification configuration. Secrets and exchange write permissions are never displayed or enabled.",
};

export default function Home() {
  const [tab, setTab] = useState("Overview");
  const [events, setEvents] = useState<Event[]>([]);
  useEffect(() => { fetch("/api/events").then((r) => r.ok ? r.json() : { items: [] }).then((d) => setEvents(d.items ?? [])).catch(() => undefined); }, []);
  const active = events.filter((event) => !event.classification.ignored);
  return <main>
    <header className="topbar"><a className="brand" href="/">EventRadar <small>READ-ONLY</small></a><nav>{tabs.map((item) => <span className="tab" key={item}><button className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button><Help text={tabInfo[item]} /></span>)}</nav><span className="safe">Auto-trading off</span></header>
    <section className="content"><div className="heading"><div><p className="eyebrow">EVENT-DRIVEN RISK MONITORING</p><h1>{tab} <Help text={tabInfo[tab]} /></h1><p>Review structured event signals and their market evidence.</p></div><span className="live">● Monitoring</span></div>
      {tab === "Overview" && <><div className="metrics"><Metric label="Active alerts" value={String(active.length)} /><Metric label="High risk" value={String(active.filter((e) => ["high", "critical"].includes(e.classification.severity ?? "")).length)} /><Metric label="Sources" value="1" /></div><div className="requirements"><Panel title="What EventRadar monitors">Security incidents, exchange policy changes, protocol or ecosystem events, KOL statements, on-chain anomalies, regulation and exchange outages.</Panel><Panel title="How alerts are decided">Events are normalized, deduplicated, classified by direction and volatility, then checked against market evidence before alert routing.</Panel><Panel title="Alert policy">WATCH stays on the dashboard. HIGH and CRITICAL require stronger evidence. No trade execution or account access is included.</Panel></div></>}
      {tab === "Alerts" ? <><div className="requirements"><Panel title="Decision fields">What happened, affected assets, direction, volatility, confidence, source reference and safe chart/source links are required fields.</Panel><Panel title="Severity routing">Low is dashboard-only. Medium, high and critical use only configured notification channels and idempotent delivery keys.</Panel><Panel title="Deduplication">Repeated source messages preserve the first event and cannot create duplicate user notifications.</Panel></div><EventTable events={events} /></> : tab === "Market" ? <><Panel title="Market verification">Price, volume, bid depth, open interest and funding are evaluated around each event. The dashboard records 1, 5, 15 and 60 minute follow-up windows.</Panel><div className="requirements"><Panel title="Current capability">Fixture verification calculates a 60-second market reaction. Live public-stream health remains explicitly not connected.</Panel><Panel title="PRD follow-up">Persist 1/5/15/60 minute reactions, including fees and slippage assumptions, before any backtest claim.</Panel><Panel title="Safety">This is an evidence screen, not a trade instruction or execution interface.</Panel></div></> : tab === "Sources" ? <div className="requirements"><Panel title="Binance announcements">Fixture-only. A documented public announcement API was not found, so no unsupported endpoint is scraped.</Panel><Panel title="Binance market data">Documented public stream adapter; no API key, account or exchange write permission is used.</Panel><Panel title="Future P0 sources">Official X/RSS, exchanges and on-chain providers remain visibly unconnected until their contract and health checks pass.</Panel></div> : tab === "Settings" ? <div className="requirements"><Panel title="Notification safety">Telegram delivers only when bot credentials are configured. Otherwise the system records development deliveries only.</Panel><Panel title="Secrets">Environment variables hold credentials. Logs, browser storage, fixtures and API responses never contain secret values.</Panel><Panel title="Operational status">PostgreSQL, Redis and Docker Compose are configured locally; production readiness needs successful health, integration and latency verification.</Panel></div> : <EventTable events={active} />}
    </section>
  </main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function Panel({ title, children }: { title: string; children: string }) { return <article className="panel"><h2>{title}</h2><p>{children}</p></article>; }
function Help({ text }: { text: string }) { return <span className="help" tabIndex={0} aria-label={text}>?<span className="tooltip" role="tooltip">{text}</span></span>; }
function EventTable({ events }: { events: Event[] }) { return <article className="panel table-wrap"><h2>Event feed <Help text="Shows normalized events after source ingestion and classification. Empty state means no event is currently persisted." /></h2>{events.length === 0 ? <p style={{ padding: "0 22px 22px" }}>No events available yet. Source and market capability details remain available in the other tabs.</p> : <table><thead><tr><th>Time</th><th>Assets</th><th>Severity</th><th>Direction</th><th>Event</th></tr></thead><tbody>{events.map((event) => <tr key={event.event_id}><td>{new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Seoul", dateStyle: "short", timeStyle: "short" }).format(new Date(event.source_timestamp))}</td><td>{event.tickers.join(", ") || "-"}</td><td><span className="tag">{event.classification.ignored ? "Ignored" : event.classification.severity}</span></td><td>{event.classification.direction ?? "-"}</td><td>{event.content}</td></tr>)}</tbody></table>}</article>; }
