"use client";

import { useEffect, useState } from "react";

type Event = { event_id: string; source_timestamp: string; content: string; tickers: string[]; classification: { severity?: string; direction?: string; ignored: boolean } };
const tabs = ["Overview", "Alerts", "Market", "Sources", "Settings"];

export default function Home() {
  const [tab, setTab] = useState("Overview");
  const [events, setEvents] = useState<Event[]>([]);
  useEffect(() => { fetch("/api/events").then((r) => r.ok ? r.json() : { items: [] }).then((d) => setEvents(d.items ?? [])).catch(() => undefined); }, []);
  const active = events.filter((event) => !event.classification.ignored);
  return <main>
    <header className="topbar"><a className="brand" href="/">EventRadar <small>READ-ONLY</small></a><nav>{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav><span className="safe">Auto-trading off</span></header>
    <section className="content"><div className="heading"><div><p className="eyebrow">EVENT-DRIVEN RISK MONITORING</p><h1>{tab}</h1><p>Review structured event signals and their market evidence.</p></div><span className="live">● Monitoring</span></div>
      {tab === "Overview" && <><div className="metrics"><Metric label="Active alerts" value={String(active.length)} /><Metric label="High risk" value={String(active.filter((e) => ["high", "critical"].includes(e.classification.severity ?? "")).length)} /><Metric label="Sources" value="1" /></div><div className="requirements"><Panel title="What EventRadar monitors">Security incidents, exchange policy changes, protocol or ecosystem events, KOL statements, on-chain anomalies, regulation and exchange outages.</Panel><Panel title="How alerts are decided">Events are normalized, deduplicated, classified by direction and volatility, then checked against market evidence before alert routing.</Panel><Panel title="Alert policy">WATCH stays on the dashboard. HIGH and CRITICAL require stronger evidence. No trade execution or account access is included.</Panel></div></>}
      {tab === "Market" ? <Panel title="Market verification">Price, volume, bid depth, open interest and funding are evaluated around each event. The dashboard records 1, 5, 15 and 60 minute follow-up windows.</Panel> : tab === "Sources" ? <Panel title="Source health">Binance announcements use a redacted contract fixture until a documented public announcement API is available. Public market data uses documented Binance streams.</Panel> : tab === "Settings" ? <Panel title="Notification safety">Telegram delivers only when bot credentials are configured. Otherwise the system records development deliveries only. Secrets are never displayed.</Panel> : <EventTable events={tab === "Overview" ? active : events} />}
    </section>
    <style jsx>{`:global(html),:global(body){margin:0;min-height:100%;background:#07111f}*{box-sizing:border-box}main{min-height:100vh;background:#07111f;color:#edf4fb;font-family:Inter,Arial,sans-serif}.topbar{height:68px;display:flex;align-items:center;gap:28px;padding:0 max(24px,calc((100vw - 1280px)/2));border-bottom:1px solid #20334b;background:#091522;position:sticky;top:0;z-index:5}.brand{color:#fff;text-decoration:none;font-size:21px;font-weight:750;white-space:nowrap}.brand small{color:#7f9abb;font-size:10px;letter-spacing:1px}nav{display:flex;gap:4px;overflow-x:auto;flex:1}button{border:0;background:transparent;color:#9db2ca;border-radius:7px;padding:9px 12px;font-size:14px;white-space:nowrap;cursor:pointer}.active,button:hover{background:#173555;color:#fff}.safe{background:#1a3045;color:#b8cee3;padding:7px 10px;border-radius:999px;font-size:12px;white-space:nowrap}.content{width:min(1180px,100%);margin:auto;padding:42px 24px}.heading{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:28px}.eyebrow{color:#6ca9e8;font-size:11px;letter-spacing:1.3px;font-weight:bold}.heading h1{margin:6px 0;font-size:32px}.heading p{color:#9fb1c7;margin:0}.live{color:#81d8ad;background:#123329;padding:8px 12px;border-radius:20px;font-size:12px}.metrics,.requirements{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-bottom:20px}.metric,.panel{background:#0d1b2b;border:1px solid #20364f;border-radius:12px}.metric{padding:20px}.metric span{color:#93a9c1;font-size:13px}.metric strong{display:block;font-size:32px;margin-top:9px}.panel{padding:22px;color:#b7c8db;line-height:1.55}.panel h2{margin-top:0;color:#fff;font-size:17px}.table-wrap{overflow-x:auto;padding:0}.table-wrap h2{padding:22px 22px 0;margin:0;color:#fff}table{width:100%;min-width:690px;border-collapse:collapse;margin-top:16px}th,td{padding:14px 22px;border-top:1px solid #20364f;text-align:left;font-size:14px}th{color:#8fa5bd;font-weight:500}.tag{background:#203b59;padding:4px 8px;border-radius:5px;font-size:12px}@media(max-width:720px){.topbar{height:auto;min-height:64px;flex-wrap:wrap;padding:12px 16px;gap:10px}.safe{display:none}nav{order:3;flex-basis:100%}.content{padding:28px 16px}.heading{display:block}.live{display:inline-block;margin-top:14px}.metrics,.requirements{grid-template-columns:1fr}.heading h1{font-size:28px}}`}</style>
  </main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function Panel({ title, children }: { title: string; children: string }) { return <article className="panel"><h2>{title}</h2><p>{children}</p></article>; }
function EventTable({ events }: { events: Event[] }) { return <article className="panel table-wrap"><h2>Event feed</h2>{events.length === 0 ? <p style={{ padding: "0 22px 22px" }}>No events available yet.</p> : <table><thead><tr><th>Time</th><th>Assets</th><th>Severity</th><th>Direction</th><th>Event</th></tr></thead><tbody>{events.map((event) => <tr key={event.event_id}><td>{new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Seoul", dateStyle: "short", timeStyle: "short" }).format(new Date(event.source_timestamp))}</td><td>{event.tickers.join(", ") || "-"}</td><td><span className="tag">{event.classification.ignored ? "Ignored" : event.classification.severity}</span></td><td>{event.classification.direction ?? "-"}</td><td>{event.content}</td></tr>)}</tbody></table>}</article>; }
